/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Optional;
import java.util.Properties;

import jakarta.servlet.ServletConfig;
import jakarta.servlet.ServletException;

// import com.zaxxer.hikari.HikariDataSource;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet(name = "home", urlPatterns = "/main/", loadOnStartup = 1)
public class App extends HttpServlet  {
	@Override
	public void init(ServletConfig config) throws ServletException {
		super.init(config);
	}
	
	public void doGet(
		HttpServletRequest req,
		HttpServletResponse resp
	) throws ServletException, IOException {
		// TODO: Rewrite the db class to make it clean (Remove Exceptions by wrapping it in Optional/Result)
		try (
			Connection cnx = DriverManager.getConnection("jdbc:postgresql://localhost/college", "postgres", "Dineshkumar4u!");
			Statement stmt = cnx.createStatement();
			PrintWriter out = resp.getWriter();
		){
			resp.setContentType("text/plain");
			String id = req.getParameter("id");
			String query = String.format("SELECT Name FROM Student WHERE RollNo=%d;", id);
			ResultSet resultSet = stmt.executeQuery(query);

			if (resultSet.next()) {
				String name = resultSet.getString("Name");
				String msg = String.format("Hello, %s!", name);
				resp.setContentLength(msg.length());
				out.println(msg);
			} else {
				String msg = "Sorry I don't know who you are!";
				resp.setContentLength(msg.length());
				out.println(msg);
			}

		} catch (SQLException e) {
			System.err.println(e.getMessage());
		}

	}
}
