/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

import com.zaxxer.hikari.HikariDataSource;

import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@WebServlet(name = "home", urlPatterns = "/", loadOnStartup = 1)
public class App extends HttpServlet  {
	public void doGet(
		HttpServletRequest req,
		HttpServletResponse resp
	) throws IOException {
		// PrintWriter out = resp.getWriter();
		// try {
		// 	HikariDataSource ds = (HikariDataSource) this.getServletContext().getAttribute("dbpool");
		// 	if (ds.isClosed()) {
		// 		out.println("Datasource is closed");
		// 		resp.setStatus(501);
		// 		return;
		// 	}
		// 	Connection cnx = ds.getConnection();
		// 	Statement s = cnx.createStatement();
		// 	boolean executed = s.execute("SELECT 'hello, world'");
		// 	if (executed) {
		// 		resp.setStatus(200);
		// 		out.println("Connection to DB successful");
		// 	} else {
		// 		resp.setStatus(501);
		// 		out.println("Cannot execute statement");
		// 	}
		// } catch (SQLException e) {
		// 	resp.setStatus(500);
		// 	out.println(e.getMessage());
		// } finally {
		// 	out.close();
		// }

	}
}
